### ISSUE TITLE
save更新数据的小建议

### ISSUE THREAD

**Issue by hadrianl** [QUANTAXIS/QUANTAXIS#247]
save目前追求数据的连续和完备，但如果是update最新数据用的话，耗时略微蛋疼。针对这个痛点稍微提出两点建议：
* 维护一个更新进度的list，新增个update命令只请求获取上次更新至今的数据。
* 另外就是mongodb里面用code和date或datetime，做复合索引，可能save时候的检索会快点。

**Comment by yutiansut** [comment]
复合索引参见 https://github.com/yutiansut/QUANTAXIS/pull/264
