### ISSUE TITLE
竞价时间段的数据处理问题

### ISSUE THREAD

**Issue by newworldnewlife** [QUANTAXIS/QUANTAXIS#271]
## 执行QA.QA_fetch_stock_min_adv('000001','2017-10-24','2017-10-25').data

  |   | code | open | high | low | close | volume | datetime | date
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

000001 | 11.20 | 11.20 | 11.19 | 11.19 | 704200.0 | 2017-10-24 09:31:00 | 2017-10-24
000001 | 11.19 | 11.21 | 11.18 | 11.21 | 494200.0 | 2017-10-24 09:32:00 | 2017-10-24
000001 | 11.20 | 11.21 | 11.20 | 11.21 | 345700.0 | 2017-10-24 09:33:00 | 2017-10-24
000001 | 11.20 | 11.21 | 11.20 | 11.20 | 221000.0 | 2017-10-24 09:34:00 | 2017-10-24
000001 | 11.21 | 11.21 | 11.20 | 11.21 | 165500.0 | 2017-10-24 09:35:00 | 2017-10-24
000001 | 11.20 | 11.21 | 11.20 | 11.21 | 181200.0 | 2017-10-24 09:36:00 | 2017-10-24
000001 | 11.21 | 11.21 | 11.20 | 11.21 | 220800.0 | 2017-10-24 09:37:00 | 2017-10-24
000001 | 11.21 | 11.22 | 11.20 | 11.22 | 336200.0 | 2017-10-24 09:38:00 | 2017-10-24
000001 | 11.22 | 11.23 | 11.21 | 11.23 | 220900.0 | 2017-10-24 09:39:00 | 2017-10-24
000001 | 11.23 | 11.24 | 11.22 | 11.23 | 411700.0 | 2017-10-24 09:40:00 | 2017-10-24
000001 | 11.22 | 11.24 | 11.22 | 11.23 | 216000.0 | 2017-10-24 09:41:00 | 2017-10-24
000001 | 11.24 | 11.25 | 11.23 | 11.24 | 254200.0 | 2017-10-24 09:42:00 | 2017-10-24
000001 | 11.24 | 11.24 | 11.23 | 11.23 | 152600.0 | 2017-10-24 09:43:00 | 2017-10-24
000001 | 11.23 | 11.24 | 11.23 | 11.23 | 438900.0 | 2017-10-24 09:44:00 | 2017-10-24
000001 | 11.24 | 11.24 | 11.23 | 11.24 | 253800.0 | 2017-10-24 09:45:00 | 2017-10-24
000001 | 11.23 | 11.25 | 11.23 | 11.25 | 413400.0 | 2017-10-24 09:46:00 | 2017-10-24
000001 | 11.24 | 11.25 | 11.24 | 11.24 | 389300.0 | 2017-10-24 09:47:00 | 2017-10-24
000001 | 11.24 | 11.25 | 11.24 | 11.25 | 370500.0 | 2017-10-24 09:48:00 | 2017-10-24
000001 | 11.25 | 11.27 | 11.25 | 11.27 | 400000.0 | 2017-10-24 09:49:00 | 2017-10-24
000001 | 11.28 | 11.29 | 11.27 | 11.29 | 1348200.0 | 2017-10-24 09:50:00 | 2017-10-24
000001 | 11.29 | 11.30 | 11.28 | 11.30 | 633700.0 | 2017-10-24 09:51:00 | 2017-10-24
000001 | 11.29 | 11.31 | 11.29 | 11.31 | 622600.0 | 2017-10-24 09:52:00 | 2017-10-24
000001 | 11.31 | 11.31 | 11.29 | 11.30 | 210200.0 | 2017-10-24 09:53:00 | 2017-10-24
000001 | 11.29 | 11.30 | 11.28 | 11.29 | 634100.0 | 2017-10-24 09:54:00 | 2017-10-24
000001 | 11.29 | 11.30 | 11.29 | 11.29 | 397500.0 | 2017-10-24 09:55:00 | 2017-10-24
000001 | 11.30 | 11.30 | 11.29 | 11.30 | 159700.0 | 2017-10-24 09:56:00 | 2017-10-24
000001 | 11.29 | 11.30 | 11.28 | 11.28 | 90200.0 | 2017-10-24 09:57:00 | 2017-10-24
000001 | 11.29 | 11.30 | 11.28 | 11.30 | 432700.0 | 2017-10-24 09:58:00 | 2017-10-24
000001 | 11.30 | 11.30 | 11.28 | 11.28 | 344500.0 | 2017-10-24 09:59:00 | 2017-10-24
000001 | 11.29 | 11.29 | 11.28 | 11.28 | 199700.0 | 2017-10-24 10:00:00 | 2017-10-24
... | ... | ... | ... | ... | ... | ... | ...
000001 | 11.38 | 11.38 | 11.37 | 11.38 | 169300.0 | 2017-10-24 14:29:00 | 2017-10-24
000001 | 11.38 | 11.38 | 11.37 | 11.38 | 89700.0 | 2017-10-24 14:30:00 | 2017-10-24
000001 | 11.37 | 11.40 | 11.37 | 11.40 | 1502700.0 | 2017-10-24 14:31:00 | 2017-10-24
000001 | 11.40 | 11.42 | 11.40 | 11.42 | 675300.0 | 2017-10-24 14:32:00 | 2017-10-24
000001 | 11.42 | 11.42 | 11.41 | 11.42 | 352400.0 | 2017-10-24 14:33:00 | 2017-10-24
000001 | 11.41 | 11.42 | 11.41 | 11.41 | 687200.0 | 2017-10-24 14:34:00 | 2017-10-24
000001 | 11.41 | 11.42 | 11.41 | 11.41 | 128900.0 | 2017-10-24 14:35:00 | 2017-10-24
000001 | 11.41 | 11.42 | 11.41 | 11.41 | 225300.0 | 2017-10-24 14:36:00 | 2017-10-24
000001 | 11.41 | 11.41 | 11.40 | 11.40 | 168000.0 | 2017-10-24 14:37:00 | 2017-10-24
000001 | 11.41 | 11.41 | 11.39 | 11.40 | 137200.0 | 2017-10-24 14:38:00 | 2017-10-24
000001 | 11.39 | 11.40 | 11.39 | 11.39 | 317000.0 | 2017-10-24 14:39:00 | 2017-10-24
000001 | 11.39 | 11.40 | 11.39 | 11.39 | 118400.0 | 2017-10-24 14:40:00 | 2017-10-24
000001 | 11.39 | 11.40 | 11.38 | 11.38 | 106200.0 | 2017-10-24 14:41:00 | 2017-10-24
000001 | 11.38 | 11.39 | 11.38 | 11.38 | 85100.0 | 2017-10-24 14:42:00 | 2017-10-24
000001 | 11.39 | 11.39 | 11.38 | 11.38 | 83800.0 | 2017-10-24 14:43:00 | 2017-10-24
000001 | 11.39 | 11.39 | 11.38 | 11.39 | 410900.0 | 2017-10-24 14:44:00 | 2017-10-24
000001 | 11.39 | 11.39 | 11.37 | 11.37 | 194400.0 | 2017-10-24 14:45:00 | 2017-10-24
000001 | 11.38 | 11.38 | 11.36 | 11.36 | 395600.0 | 2017-10-24 14:46:00 | 2017-10-24
000001 | 11.38 | 11.38 | 11.36 | 11.36 | 163300.0 | 2017-10-24 14:47:00 | 2017-10-24
000001 | 11.36 | 11.37 | 11.36 | 11.37 | 110700.0 | 2017-10-24 14:48:00 | 2017-10-24
000001 | 11.36 | 11.37 | 11.36 | 11.36 | 111400.0 | 2017-10-24 14:49:00 | 2017-10-24
000001 | 11.36 | 11.37 | 11.35 | 11.35 | 412500.0 | 2017-10-24 14:50:00 | 2017-10-24
000001 | 11.35 | 11.36 | 11.35 | 11.35 | 191400.0 | 2017-10-24 14:51:00 | 2017-10-24
000001 | 11.35 | 11.37 | 11.35 | 11.37 | 241000.0 | 2017-10-24 14:52:00 | 2017-10-24
000001 | 11.36 | 11.39 | 11.35 | 11.38 | 581800.0 | 2017-10-24 14:53:00 | 2017-10-24
000001 | 11.37 | 11.39 | 11.37 | 11.37 | 184400.0 | 2017-10-24 14:54:00 | 2017-10-24
000001 | 11.36 | 11.39 | 11.36 | 11.39 | 279000.0 | 2017-10-24 14:55:00 | 2017-10-24
000001 | 11.37 | 11.39 | 11.37 | 11.38 | 164800.0 | 2017-10-24 14:56:00 | 2017-10-24
000001 | 11.38 | 11.39 | 11.37 | 11.38 | 134100.0 | 2017-10-24 14:57:00 | 2017-10-24
000001 | 11.39 | 11.39 | 11.39 | 11.39 | 562000.0 | 2017-10-24 15:00:00 | 2017-10-24

## 14：58、14：59竞价阶段，成交量为0，但数据中不应该剔除。

**Comment by yutiansut** [comment]
是这样的 有时候拿回来的停牌股票数据  他会有价格 但是没有交易量  就被我剔除了...

我考虑考虑怎么洗这个数据

**Comment by doskoi** [comment]
0的同时去查查上一个交易日有没有交易量，基本停牌的都能过滤掉。

**Comment by yutiansut** [comment]
停牌的数据不是0 是那种10-6方左右的小数
