### ISSUE TITLE
对回测的Web端的分析报告的几点建议。

### ISSUE THREAD

**Issue by Wier123** [QUANTAXIS/QUANTAXIS#370]
#1.加入“每次进场和退场的时间和成交价”（不知是不是就是“成交明细'页面想体现的，总感觉好乱，要找半天。）[例：附件图.（像这样就很清晰）。](https://wx2.sinaimg.cn/mw690/b8d46e2dgy1fm5omsjualj20rp0cpt9d.jpg)
这项我觉得是大家都会要用来核对的。一是核对平台回测策略的执行是否和想要的一直，而是核对回测计算是否有误，还可以看出一些亏损或者盈利的交易分布是不是够分散。
**哦的确是成交明细里的内容。那我看错了。不用了这项多余了。抱歉。**

2.收益期望值：（所有盈利交易的盈利总和/交易总次数） / （所有亏损交易的亏损总和/亏损的次数）
看到“业绩表现”页面已经有“胜率”这一项，所以可以把上面的公式变为：（1-胜率） x (所有盈利交易的盈利总和 / 所有亏损交易的亏损总和)
这项其实就是撒普的收益期望值公式，一个摩根实习的朋友说不少人看重这项，所以应该不少人要的。

3.交易总次数。
这项我猜肯定很多人需要的，无论是从证券行业的惯例还是统计学的样本数要求，都会有自己规定的最低必须次数。

4.最大连续亏损交易次数。

5.最大一笔亏损的亏损金额。

求。希望报告中有这几个。。。谢谢。这样的报告我觉得基本应该是足够满意的，无论是个人和一些小机构都能满足的。谢谢
QQ:Jokev1。

**Comment by Wier123** [comment]
@yutiansut 1.3.45也很重要的啊(っ´Ι`)っ

**Comment by Wier123** [comment]
@yutiansut 看错。第一项的确是成交明细里的内容。那我看错了。不用了这项多余了。抱歉。重复了。抱歉

**Comment by better319** [comment]
不错不错应邀来顶一下
